name: Build and Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release'
        required: true
        default: '0.0.0'

jobs:
  build:
    permissions:
      contents: write
    runs-on: macos-13
    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        brew install autoconf
        brew install automake
        brew install libtool
        brew install texinfo
        python -m pip install setuptools

    - name: Build
      run: |
        swift run --package-path scripts build enable-gnutls

    - name: Cache Primes
      id: cache-primes
      uses: actions/cache/save@v4
      with:
        path: ./dist
        key: gnutls-primes